#
# Constants
#

# The midi note resolution. This resolution lets up support up to 24 notes/beat. If a midi track is supplied
# with a smaller resolution, it gets rejected. Nobody was composing classical music at that resolution.
RESOLUTION = 24

EIGHTH_NOTE = RESOLUTION / 2
DOTTED_EIGHTH_NOTE = int(EIGHTH_NOTE * 1.5)
SIXTEENTH_NOTE = RESOLUTION / 4
DOTTED_SIXTEENTH_NOTE = int(SIXTEENTH_NOTE * 1.5)
THIRTY_SECOND_NOTE = RESOLUTION / 8
EIGHT_NOTE_TRIPLET = RESOLUTION / 3
SIXTEENTH_NOTE_TRIPLET = RESOLUTION / 6
THIRTY_SECOND_NOTE_TRIPLET = RESOLUTION / 12
QUARTER_NOTE = RESOLUTION

SUBDIVISIONS = (EIGHTH_NOTE, SIXTEENTH_NOTE, THIRTY_SECOND_NOTE, EIGHT_NOTE_TRIPLET, SIXTEENTH_NOTE_TRIPLET,
                THIRTY_SECOND_NOTE_TRIPLET, QUARTER_NOTE, DOTTED_EIGHTH_NOTE, DOTTED_SIXTEENTH_NOTE)

DEFAULT_VELOCITY = 120
